## Promise

자바스크립트와 노드에서는 주로 **비동기**를 접한다

특히 이벤트 리스너를 사용할 때 콜백 함수를 자주 사용

> ES2015부터는 자바스크립트와 노드의 API들이 콜백 대신 프로미스(Promise) 기반으로 재구성

악명높은 콜백 지옥 현상을 극복했다는 평가를 받는다

**$*$ 프로미스는 반드시 알아둬야 하는 객체**

프로미스 규칙 - 먼저 프로미스 객체를 생성

```javascript
const condition = true; // true이면 resolve, false이면 reject
const promise = new Promise((resolve, reject) => {
   if (condition) {
      resolve('성공');
   } else {
      reject('실패');
   }
});
// 다른 코드가 들어갈 수 있음
promise
   .then(message => {
      console.log(message); // 성공(resolve)한 경우 실행
   })
   .catch(error => {
      console.error(error); // 실패(reject)한 경우 실행
   })
   .finally(() => {
      // 끝나고 무조건 실행
      console.log('무조건');
   });
```

`new Promise`로 프로미스를 생성할 수 있으며, 안에 resolve와 reject를 매개변수로 갖는 콜백 함수를 넣는다

이렇게 만든 `promise` 변수에 `then`과 `catch` 메서드를 붙일 수 있다

→ 프로미스 내부에서 resolve가 호출되면 `then`이 실행되고, reject가 실행되면 `catch`가 실행된다

resolve와 reject에 넣어준 인수는 각각 `then`과 `catch`의 매개변수에서 받을 수 있다!

> 즉, `resolve('성공')`이 호출되면 `then`의 message가 `'성공'`이 된다

> 만약 `reject('실패')`가 호출되면 `catch`의 error가 `'실패'`rk ehlsms rjt

`condition`의 변수를 `false`로 바꿔보면 `catch`에서 에러가 로깅된다

> 프로미스 : **실행은 하되 결괏값은 나중에 받는 객체**

결괏값은 실행이 완료된 후 `then`이나 `catch` 메서드를 통해 받는다

`new Promise`는 바로 실행이 되지만, 결괏값은 `then`을 붙였을 때 받게 된다

$*$ `then`이나 `catch`에서 다시 다른 `then`이나 `catch`를 붙일 수 있다

```javascript
promise
   .then(message => {
      return new Promise((resolve, reject) => {
         resolve(message);
      });
   })
   .then(message2 => {
      console.log(message2);
      return new Promise((resolve, reject) => {
         resolve(message2);
      });
   })
   .then(message3 => {
      console.lgo(message3);
   })
   .catch(error => {
      console.error(error);
   });
```

처음 `then`에서 `message`를 `resolve`하면 다음 `then`에서 `message2`로 받을 수 있다 (반복)

단, `then`에서 `new Promise`를 `return`해야 다음 `then`에서 받을 수 있다

## 콜백 함수를 프로미스로 바꾸기

$*$ 콜백을 쓰는 패턴 중 하나

```javascript
function findAndSaveUser(Users) {
   Users.findOne({}, (err, user) => {
      // 첫 번째 콜백
      if (err) {
         return console.error(err);
      }
      user.name = 'zero';
      user.save(err => {
         // 두 번째 콜백
         if (err) {
            return console.error(err);
         }
         Users.findOne({ gender: 'm' }, (err, user) => {
            // 세 번째 콜백
            // 생략
         });
      });
   });
}
```

콜백 함수가 세 번 중첩되어 있고, 콜백 함수가 나올 때마다 코드의 깊이가 깊어진다

또한 각 콜백 함수마다 에러도 따로 처리해주어야 한다

$*$ 콜백함수로 바꾸기

```javascript
function findAndSaveUser(Users) {
   Users.findOne({})
      .then(user => {
         user.name = 'zero';
         return user.save();
      })
      .then(user => {
         return Users.findOne({ gender: 'm' });
      })
      .then(user => {
         // 생략
      })
      .catch(err => {
         console.error(err);
      });
}
```

-  코드의 깊이가 세 단계 이상 깊어지지 않는다
-  `then` 메서드들은 순차적으로 실행된다
-  에러도 마지막 `catch`에서 한 번에 처리할 수 있다

> 모든 콜백 함수를 프로미스로 변환할 수 있는 것은 아니다! 메서드가 프로미스 방식을 지원해야 한다 <br>
> (예제 코드는 `findOne`과 `save`메서드가 내부적으로 프로미스 객체를 갖고 있다고 가정했기에 가능하다)

## 프로미스 여러 개를 한 번에 실행하기

기존의 콜백 패턴이었다면 콜백을 여러 번 중첩해서 사용해야 했지만 `Promise.all`을 활용하면 간단하게 할 수 있다

```javascript
const promise1 = Promise.resolve('성공1');
const promise2 = Promise.resolve('성공2');
Promise.all([promise1, promise2])
   .then(result => {
      console.log(result); // ['성공1', '성공2'];
   })
   .catch(error => {
      console.error(error);
   });
```

`Promise.resolve`는 즉시 `resolve`하는 프로미스를 만드는 방법이다

프로미스가 여러 개 있을 때 `Promise.all`에 넣으면 모두 resolve 될 떄까지 기다렸다가 `then`으로 넘어간다

`result` 매개변수에 각각의 프로미스 결괏값이 배열로 들어있다

Promise 중 하나라도 reject가 되면 catch로 넘어간다 (단, 여러 프로미스 중 어떤 프로미스가 reject 되었는 지는 알 수 없다)

## `Promise.allSettled`

정확히 어떤 프로미스에서 reject되었는지 알기 위해서는 `Promise.allSettled`를 사용해야 한다

```javascript
const promise1 = Promise.resolve('성공1');
const promise2 = Promise.reject('실패2');
const promise3 = Promise.resolve('성공3');
Promise.allSettled([promise1, promise2, promise3])
   .then(result => {
      console.log(result);
      /*   [
          { status: 'fulfilled', value: '성공1' },
          { status: 'rejected', reason: '실패2' },
          { status: 'fulfilled', value: '성공3' },
          
        ]
        */
   })
   .catch(error => {
      console.error(error);
   });
```

결괏값이 더 자세하기 떄문에 어떤 프로미스가 reject 되었는지 status를 통해서 알 수 있다

reason에 들어있다 따라서 Promise.all보다 Promise.allSettled를 더 권장한다

$*$ Node 16 버전부터 reject 된 Promise에 catch를 달지 않으면 UnhandledPromiseRejection 에러가 발생한다 (에러가 발생하면 다음 코드가 실행되지 않음)

> 반드시 Promise에 `catch` 메서드를 붙이는 것을 권장
